plugins { id 'com.android.application' }
android {
    namespace 'com.shaterguy.soopdownloader'
    compileSdk 35
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    defaultConfig {
        applicationId 'com.shaterguy.soopdownloader'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes {
        debug { applicationIdSuffix '.debug'; versionNameSuffix '-debug' }
        release { minifyEnabled false }
    }
    testOptions { unitTests.returnDefaultValues = true }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
